### Reverseing the rows of array

In [1]:
import numpy as np

In [2]:
arr = np.arange(16)

In [5]:
arr = arr.reshape(4,4)

In [6]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [7]:
new_arr = arr[::-1]

In [8]:
new_arr

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

### Reversing the Elements 

In [11]:
new_arr = arr[::-1, ::-1]

In [12]:
new_arr

array([[15, 14, 13, 12],
       [11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])