### Filling Diagonal values

In [1]:
import numpy as np

In [8]:
arr = np.array([[9,8],[6,7]])

In [9]:
arr

array([[9, 8],
       [6, 7]])

In [4]:
x = 5

In [7]:
### 1 way 

for i in range(len(arr)):
    for j in range(len(arr[i])):
        if i == j :
            arr[i][j] =5
print(arr)

[[5 8]
 [6 5]]


In [10]:
# 2 Way

arr

array([[9, 8],
       [6, 7]])

In [12]:
np.fill_diagonal(arr,x)
print(arr)

[[5 8]
 [6 5]]


### Checking and Filling number

In [15]:
arr1 = np.array([12,23,-43,24,-8,76,-56,66,88,-3])
print(arr1)

[ 12  23 -43  24  -8  76 -56  66  88  -3]


In [17]:
np.isin(arr1, [12,66,24])

array([ True, False, False,  True, False, False, False,  True, False,
       False])

In [20]:
arr1[arr1 < 0]

array([-43,  -8, -56,  -3])

In [ ]:
arr1[arr1 < 0]
