### NumPy

In [9]:
import numpy as np

In [10]:
l1 = [1,2.3,'data']

In [11]:
print(l1)

[1, 2.3, 'data']


In [12]:
a = np.array(l1)
print(a)

['1' '2.3' 'data']


In [7]:
print(a, type(a))

['1' '2.3' 'data'] <class 'numpy.ndarray'>


In [13]:
a.ndim

1

In [14]:
a.size

3

In [15]:
a.shape

(3,)

In [43]:
a.dtype

dtype('<U32')

In [24]:
l1 = [1,2,3,5,6]
l2 = [20,40,60,70,80]
print(l1 + l2)

[1, 2, 3, 5, 6, 20, 40, 60, 70, 80]


In [25]:
a1 = np.array([1,2,3,5,6])
a2 = np.array([20,40,60,70,80])
print(a1 + a2)

[21 42 63 75 86]


In [26]:
a1 = np.array(l1)
a2 = np.array(l2)
print(a1 + a2)

[21 42 63 75 86]


In [44]:
a1.dtype

dtype('int64')

In [27]:
a1**2

array([ 1,  4,  9, 25, 36])

In [41]:
my_matrix = [[1,2,3,4],[5,6,7,'eight'],[9,10,11,12]]
my_matrix

[[1, 2, 3, 4], [5, 6, 7, 'eight'], [9, 10, 11, 12]]

In [36]:
b = np.array(my_matrix)
b

array([['1', '2', '3', '4'],
       ['5', '6', '7', 'eight'],
       ['9', '10', '11', '12']], dtype='<U21')

In [37]:
type(b)

numpy.ndarray

In [38]:
b.ndim

2

In [39]:
b.size

12

In [40]:
b.shape

(3, 4)

In [42]:
b.dtype

dtype('<U21')

In [49]:
lst1 = [[[1,2,10],[3,4,5]], [[5,6,7],[7,8,9]]]

arr1 = np.array(lst1)
arr1

array([[[ 1,  2, 10],
        [ 3,  4,  5]],

       [[ 5,  6,  7],
        [ 7,  8,  9]]])

In [50]:
arr1.shape

(2, 2, 3)

In [52]:
arr1[1][0][1]

np.int64(6)

In [54]:
arr4 = [[[[1,2,3,5]]]]
arr4 =  np.array(arr4)

In [55]:
arr4

array([[[[1, 2, 3, 5]]]])

In [56]:
arr4.shape

(1, 1, 1, 4)

In [57]:
arr4[0][0][0][2]

np.int64(3)

In [58]:
arr1

array([[[ 1,  2, 10],
        [ 3,  4,  5]],

       [[ 5,  6,  7],
        [ 7,  8,  9]]])

In [60]:
arr1.size

12

In [70]:
a2=arr1.reshape(1,2,1,6)
a2

array([[[[ 1,  2, 10,  3,  4,  5]],

        [[ 5,  6,  7,  7,  8,  9]]]])

In [71]:
a3=arr1.reshape(1,1,12,1)
a3

array([[[[ 1],
         [ 2],
         [10],
         [ 3],
         [ 4],
         [ 5],
         [ 5],
         [ 6],
         [ 7],
         [ 7],
         [ 8],
         [ 9]]]])

In [72]:
a4=arr1.reshape(1,1,1,12)
a4

array([[[[ 1,  2, 10,  3,  4,  5,  5,  6,  7,  7,  8,  9]]]])

In [74]:
a5 = arr1.reshape(2,3,2)
a5

array([[[ 1,  2],
        [10,  3],
        [ 4,  5]],

       [[ 5,  6],
        [ 7,  7],
        [ 8,  9]]])

In [77]:
a6 = arr1.reshape(1,4,3)
a6

array([[[ 1,  2, 10],
        [ 3,  4,  5],
        [ 5,  6,  7],
        [ 7,  8,  9]]])

In [82]:
b2=arr1.reshape(-1)
b2

array([ 1,  2, 10,  3,  4,  5,  5,  6,  7,  7,  8,  9])

In [81]:
b2.ndim

1

In [83]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])