In [1]:
import numpy as np

In [12]:
arr1 = np.zeros((3,3))

In [13]:
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
arr2 = np.ones((2,3))
arr2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
arr3 = np.full((3,3),4)
arr3

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

### Identity matrix

In [18]:
idArr = np.eye(3)
idArr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
arr4 = np.array([1.2,2.3,3.4])
arr4

array([1.2, 2.3, 3.4])

In [22]:
print(arr4.dtype)

float64


In [21]:
arr5 = arr4.astype(int)
print(arr5)
print(arr5.dtype)

[1 2 3]
int64


In [24]:
Arr = np.array([10,20,30,40,50])

print(Arr + 5)
print(Arr * 2)
print(Arr ** 2)


[15 25 35 45 55]
[ 20  40  60  80 100]
[ 100  400  900 1600 2500]


In [25]:
print(np.sum(Arr))

150


In [26]:
print(np.mean(Arr))

30.0


In [27]:
print(np.min(Arr))

10


In [28]:
print(np.max(Arr))

50


In [29]:
print(np.std(Arr))

14.142135623730951


In [30]:
print(np.var(Arr))

200.0
