### Multiply String in Numpy`

In [1]:
import numpy as np

In [2]:
arr = np.array(['Apple','Mango','Orange','Banana'])

In [3]:
print(arr)

['Apple' 'Mango' 'Orange' 'Banana']


In [6]:
new_arr = np.char.multiply(arr,2)

In [7]:
print(new_arr)

['AppleApple' 'MangoMango' 'OrangeOrange' 'BananaBanana']


### Minimum value along row and column

In [12]:
my_arr = np.array([[10,22,45],[4,5,6],[2,4,8]])
print(my_arr)

[[10 22 45]
 [ 4  5  6]
 [ 2  4  8]]


In [13]:
my_arr.shape

(3, 3)

In [15]:
np.apply_along_axis(lambda x : np.min(x),arr = my_arr,axis=0)

array([2, 4, 6])

In [16]:
np.apply_along_axis(lambda x : np.min(x),arr = my_arr,axis=1)

array([10,  4,  2])