In [1]:
import numpy as np 

In [2]:
arr = np.array([1,2, np.nan, 4, np.nan, 6])
print(np.isnan(arr))

[False False  True False  True False]


In [3]:
clean = np.nan_to_num(arr)
print(clean)

[1. 2. 0. 4. 0. 6.]


In [4]:
clean2 = np.nan_to_num(arr, nan=10)
print(clean2)

[ 1.  2. 10.  4. 10.  6.]


In [5]:
arr1 = np.array([1,2, np.inf, 4, -np.inf, 6])
print(np.isinf(arr1))

[False False  True False  True False]


In [6]:
cleaned = np.nan_to_num(arr1, posinf=10, neginf=-10)
print(cleaned)

[  1.   2.  10.   4. -10.   6.]
