In [1]:
import numpy as np

In [5]:
arr = np.array([[1,2,3,4,5],
               [2,56,7,54,32],
               [11,3,67,8,6],
               [3,4,6,5,7], 
               [6,7,5,3,2]])

In [6]:
x = 10

In [7]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 2, 56,  7, 54, 32],
       [11,  3, 67,  8,  6],
       [ 3,  4,  6,  5,  7],
       [ 6,  7,  5,  3,  2]])

In [8]:
np.any(arr > x, axis=1)

array([False,  True,  True, False, False])

In [9]:
np.where(np.any(arr > x, axis=1))

(array([1, 2]),)

In [10]:
arr[np.any(arr > x, axis=1)]

array([[ 2, 56,  7, 54, 32],
       [11,  3, 67,  8,  6]])