In [2]:
import numpy as np

In [3]:
prices = np.array([100,200,300,400,500])
disount = 10

final_prices = prices - (prices * disount / 100)
print(final_prices)

[ 90. 180. 270. 360. 450.]


In [4]:
matrix = np.array([[1,2,3],[4,5,6]])
vector = np.array([10,20,30])
result = matrix + vector
print(result)

[[11 22 33]
 [14 25 36]]


In [ ]:
arr1 = np.array()