### Compare Two array

In [2]:
import numpy as np

In [3]:
a = np.array([121,23,45])
b = np.array([234,12,42])

In [4]:
a > b

array([False,  True,  True])

In [5]:
np.greater(a, b)

array([False,  True,  True])

In [6]:
a >= b

array([False,  True,  True])

In [7]:
np.greater_equal(a,b)

array([False,  True,  True])