### Calculate sin and cos

In [1]:
import numpy as np

In [2]:
angArr = np.array([0,30,45,60,90])

In [4]:
### degree to radian

angArr = angArr * np.pi/180

In [5]:
angArr

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [6]:
np.sin(angArr)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [7]:
np.cos(angArr)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])