### Remove single dimension 

In [1]:
import numpy as np

In [2]:
arr = np.array([[[2,3,4],[6,5,4]]])

In [4]:
print(arr)

[[[2 3 4]
  [6 5 4]]]


In [5]:
arr.shape

(1, 2, 3)

In [6]:
arr = np.squeeze(arr)

In [7]:
arr.shape

(2, 3)

In [9]:
print(arr)

[[2 3 4]
 [6 5 4]]


In [10]:
3 in arr

True