### 10 zeros, 10 ones and 10 fives

In [1]:
import numpy as np

In [2]:
arr1 = np.zeros(10)

In [3]:
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
arr2 = np.ones(10)

In [5]:
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
arr3 = arr2 * 5

In [7]:
arr3

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

### Random sequences

In [8]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [11]:
b = np.repeat(a,3)
b

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [12]:
c = np.tile(a,3)
c

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [13]:
np.concatenate([b,c])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

### Get the memory size

In [14]:
my_arr = np.array([1,7,13,105])

In [15]:
print(my_arr)

[  1   7  13 105]


In [16]:
my_arr.itemsize

8

In [17]:
my_arr.size

4