In [1]:
import numpy as np

In [12]:
arr1 = np.array([23,12,63,45,76,45,45,56,98])

In [13]:
print(arr1)

[23 12 63 45 76 45 45 56 98]


In [14]:
arr2 = np.array([4,5,6])

In [15]:
print(arr2)

[4 5 6]


In [16]:
arr1.put([1,5,7],arr2)

In [17]:
arr1

array([23,  4, 63, 45, 76,  5, 45,  6, 98])

### Deleting and inserting

In [19]:
array1 = np.array([[1,23,43],[4,5,6],[8,7,5]])

In [20]:
print(array1)

[[ 1 23 43]
 [ 4  5  6]
 [ 8  7  5]]


In [21]:
column = np.array([10,20,30])

In [22]:
array1 = np.delete(array1,1,axis=1)

In [23]:
array1

array([[ 1, 43],
       [ 4,  6],
       [ 8,  5]])

In [ ]:
np.insert(array1,1,axis=1,)