### Array Modification

#### In Vector

In [2]:
import numpy as np

In [3]:
arr = np.array([10,20,30,40,50,60,70,80,90])
print(arr)

[10 20 30 40 50 60 70 80 90]


In [4]:
new_arr = np.insert(arr,3,100)
print(new_arr)

[ 10  20  30 100  40  50  60  70  80  90]


#### In Matrix

In [5]:
arr_2d = np.array([[1,2],[3,4]])
print(arr_2d)

[[1 2]
 [3 4]]


In [6]:
new_arr_2d = np.insert(arr_2d, 1, [5,6], axis=0)
print(new_arr_2d)

[[1 2]
 [5 6]
 [3 4]]


In [7]:
new_arr_2d = np.insert(arr_2d, 1, [5,6], axis=1)
print(new_arr_2d)

[[1 5 2]
 [3 6 4]]


In [8]:
new_arr_2d = np.insert(arr_2d, 1, [5,6], axis=None)
print(new_arr_2d)

[1 5 6 2 3 4]


In [9]:
np.append(arr_2d,[5,6])

array([1, 2, 3, 4, 5, 6])

In [10]:
arr1 = [1,2]
arr2 = [3,4]

In [11]:
np.concatenate((arr1,arr2), axis = 0)

array([1, 2, 3, 4])

In [12]:
np.concat((arr1,arr2),axis = 0)

array([1, 2, 3, 4])

In [13]:
arr = np.array([10,20,30,40,50,60,70,80,90])
print(arr)

[10 20 30 40 50 60 70 80 90]


In [14]:
a = np.delete(arr, 2)

In [15]:
print(a)

[10 20 40 50 60 70 80 90]


In [17]:
arr1_2d = np.array([[1,2,3],[4,5,6]])
arr1_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
a1 = np.delete(arr1_2d, 0, axis= 0)
print(a1)

[[4 5 6]]


In [19]:
arr1 = [1,2,5]
arr2 = [3,4,6]

In [20]:
print(np.hstack((arr1,arr2)))
print(np.vstack((arr1,arr2)))

[1 2 5 3 4 6]
[[1 2 5]
 [3 4 6]]


In [21]:
arr = np.array([10,20,30,40,50,60,70,80,90])

In [24]:
np.split(arr,3)

[array([10, 20, 30]), array([40, 50, 60]), array([70, 80, 90])]