### Indexing and Slicing

In [1]:
import numpy as np

In [6]:
arr = np.array([10,20,30,40,50,60,70,80,90,100])


In [7]:
print(arr[0])

10


In [8]:
print(arr[-1])

100


In [9]:
print(arr[1:5])

[20 30 40 50]


In [10]:
print(arr[0:10:2])

[10 30 50 70 90]


In [11]:
print(arr[:6])

[10 20 30 40 50 60]


In [12]:
print(arr[::-1])

[100  90  80  70  60  50  40  30  20  10]


In [15]:
print(arr[[0,2,5,6]])

[10 30 60 70]


### Filtering

In [16]:
print(arr[arr>45])

[ 50  60  70  80  90 100]


In [17]:
print(arr[arr<55])


[10 20 30 40 50]


### Reshaping and Manipulating

In [21]:
arr2 = np.array([1,2,3,4,5,6])

In [23]:
reshape = arr2.reshape(2,3)

In [24]:
print(reshape)

[[1 2 3]
 [4 5 6]]


In [25]:
reshape = arr2.reshape(3,2)
print(reshape)

[[1 2]
 [3 4]
 [5 6]]


### Falttening Array

In [26]:
flat = reshape.flatten() # Creates a copy 

In [28]:
print(flat)

[1 2 3 4 5 6]


In [29]:
reshape.ravel() # creates a view 

array([1, 2, 3, 4, 5, 6])