In [1]:
import numpy as np

In [2]:
arr = np.zeros(5)

In [3]:
arr

array([0., 0., 0., 0., 0.])

In [4]:
arr1 = np.zeros((3,4))

In [5]:
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
arr2 = np.zeros((2,3), dtype = 'int')

In [7]:
arr2

array([[0, 0, 0],
       [0, 0, 0]])